#pragma once

#include <iostream>
#include <string>
#include <memory>
#include <tuple>
#include <fstream>
#include <optional>
#include <variant>
#include <any>
#include <cmath>
#include <array>
#include <vector>
#include <unordered_map>
#include <map>
#include <algorithm>
#include <deque>
#include <stack>
#include <set>
#include <mutex>
#include <functional>
#include <cstddef>
#include <thread>
#include <numeric>
#include <shared_mutex>
#include <queue>
#include <future>
#include <atomic>
#include <cassert>